### ISSUE TITLE
cannot compile hector_quadrotor

### ISSUE THREAD

**Issue by wilhem** [tu-darmstadt-ros-pkg/hector_quadrotor#16]
Hi, I ve Indigo (Ubuntu 14.10) and I downloaded the hector_quadrotor (indigo_devel) but I cannot compile it.
The error I get is:

:~/workspace_ros$ rosdep install --from-path src --ignore-src
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
hector_quadrotor_gazebo_plugins: Cannot locate rosdep definition for [hector_gazebo_plugins]
hector_quadrotor_gazebo: Cannot locate rosdep definition for [message_to_tf]
hector_quadrotor_pose_estimation: Cannot locate rosdep definition for [hector_pose_estimation]
hector_quadrotor_demo: Cannot locate rosdep definition for [hector_gazebo_worlds]
hector_quadrotor_description: Cannot locate rosdep definition for [hector_sensors_description]

even if the error was solved here: https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/issues/4
I did the same but that solution doesn t work.
Any help is appreciated!
Thanks!!

**Comment by meyerj** [comment]
hector_quadrotor and its dependencies hector_models, hector_gazebo and hector_localization were released just a few days ago in indigo. The packages have not yet been synced to the public repositories.

So you either have to wait a few days or...
- ...temporarily switch to the ros-shadow-fixed variant of the ROS package repository by updating your /etc/apt/sources.list.d/ros-latest.list file to:
  
  ```
  deb http://packages.ros.org/ros-shadow-fixed/ubuntu utopic main
  ```
  
  and then execute `sudo apt-get update`, `rosdep update` and `rosdep install --from-path src --ignore-src` again.

or
- ...add all hector_\* dependencies to your catkin workspace, e.g. by merging hector_quadrotor.rosinstall:
  
  ```
  cd ~/workspace_ros/src
  wstool merge https://raw.githubusercontent.com/tu-darmstadt-ros-pkg/hector_quadrotor/hydro-devel/hector_quadrotor.rosinstall
  wstool update
  ```

**Comment by meyerj** [comment]
I just noticed that ROS does not provide pre-compiled packages for utopic. I assume you installed everything from source.

In this case you have to try the last option.

**Comment by wilhem** [comment]
Thanks,
but it doesn t work neither:
I have the error:

ERROR in config: Command requires a target workspace.

Regards

**Comment by meyerj** [comment]
Well, it depends on how you created your catkin workspace. The "standard" way to do it is to use tools like wstool, rosinstall or rosinstall_generator to manage the source repositories in the src folder.

If you do not have a `src/.rosinstall` file yet, simply create one with `wstool init`. Do not forget to cd into the `src` folder first (or always add `-t src` to the wstool command line).

**Comment by wilhem** [comment]
Danke Dir,
nur...ist es mir eben gerade aufgefallen, dass ich den Quadrotor auch durch:
sudo apt-get install ros-indigo-hector-*
installieren kann.
Ist es vielleicht nicht der beste Weg?

Vielen Dank nochmal.
Gruß

**Comment by meyerj** [comment]
The binary packages of hector_quadrotor for ROS indigo are available in the public repository since yesterday. See http://lists.ros.org/pipermail/ros-users/2014-September/068914.html.

If you don't want to develop or extend hector_quadrotor, the binary packages should be fine.
