### ISSUE TITLE
Problem during installation 

### ISSUE THREAD

**Issue by SensorNetworks** [tu-darmstadt-ros-pkg/hector_quadrotor#17]
I used the source code method to build the "Quadrotor outdoor flight demo" as the ros-hydro-hector-quadrotor-demo cannot be located. However, I cannot proceed with installation as I always encountered the following error message when doing "catkin_make", as shown in the following:

viki@c3po:~hector_quadrotor_tutorial$ catkin_make

........
........
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'eigen3'
--   found eigen3, version 3.2.0
-- Found Eigen: /usr/include/eigen3  
-- Eigen found (include: /usr/include/eigen3)
-- +++ processing catkin package: 'hector_geotiff_plugins'
-- ==> add_subdirectory(hector_slam/hector_geotiff_plugins)
-- Using these message generators: gencpp;genlisp;genpy
-- +++ processing catkin package: 'hector_marker_drawing'
-- ==> add_subdirectory(hector_slam/hector_marker_drawing)
-- Eigen found (include: /usr/include/eigen3)
-- +++ processing catkin package: 'hector_quadrotor_controller'
-- ==> add_subdirectory(hector_quadrotor/hector_quadrotor_controller)
-- Using these message generators: gencpp;genlisp;genpy
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by
  "hardware_interface" with any of the following names:

```
hardware_interfaceConfig.cmake
hardware_interface-config.cmake
```

  Add the installation prefix of "hardware_interface" to CMAKE_PREFIX_PATH or
  set "hardware_interface_DIR" to a directory containing one of the above
  files.  If "hardware_interface" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  hector_quadrotor/hector_quadrotor_controller/CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/viki/hector_quadrotor_tutorial/build/CMakeFiles/CMakeOutput.log".
See also "/home/viki/hector_quadrotor_tutorial/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
...

Could you help fix this?

**Comment by meyerj** [comment]
Make sure that all dependencies are installed before you compile from source. The standard approach is to use the the [rosdep](http://wiki.ros.org/rosdep) tool for that. The wiki page is a little bit outdated. I could only find the important command line for catkin workspaces in a ROS answers post [here](http://answers.ros.org/question/75241/install-ros-dependencies-from-apt/):

```
cd ~/~hector_quadrotor_tutorial
rosdep install --from-path src --ignore-src --rosdistro indigo
```

This will install all dependencies of packages found in the `src` folder. The `rosdep install [package]` approach found in the wiki does not work for catkin workspaces.

Perhaps we should add this command to the tutorials at http://wiki.ros.org/hector_quadrotor/Tutorials, but on the other side this topic deserves a more general tutorial "How to build packages from source" in the ROS wiki as it is not hector_quadrotor specific. I could not find one.
