### ISSUE TITLE
state_topic?

### ISSUE THREAD

**Issue by slremy** [tu-darmstadt-ros-pkg/hector_quadrotor#18]
Hello all, are there directions on the best approach to setting the pose (position, orientation) for the simulated quadrotor?

I've composed the message I'd like to use:
            msg.pose.pose.position = Point(x, y, z);
            quat = tf.transformations.quaternion_from_euler(phi, theta, psi);
            msg.pose.pose.orientation  = Quaternion(*quat);
            msg.twist.twist.linear = Vector3(p, q, r);
            self.odom_pub.publish(msg);

But I'm at a bit of a loss about how to set up the launch files (or SDF files?) to permit the state of the quadrotor to the set with data received from an external source. What needs to be set?

http://answers.gazebosim.org/question/7036/using-hector_quadrotor_gazebo-with-externally/

**Comment by meyerj** [comment]
Answered at Gazebo Answers:
http://answers.gazebosim.org/question/7036/using-hector_quadrotor_gazebo-with-externally#7162
