### ISSUE TITLE
about quadrotor 

### ISSUE THREAD

**Issue by nuriozalp** [tu-darmstadt-ros-pkg/hector_quadrotor#20]
when i give this command to quadrotor : rostopic pub /cmd_vel geometry_msgs/Twist -r 1 '[0, 0, 0.5]' '[0, 0, 0]'

quadrotor is not stoping after i terminate. whats the matter about quadrotor ?????????

**Comment by nuriozalp** [comment]
i think there is a error about sonar model?

**Comment by meyerj** [comment]
> quadrotor is not stoping after i terminate. whats the matter about quadrotor ?????????

That's normal. There is no timeout implemented in the velocity command input and the quadrotor just continues with the last velocity command received. You do not have to repeat it periodically (`-r 1` can be omitted).

If you want to stop the quadrotor you have to publish a command with all values set to zero, e.g. with rostopic:

```
rostopic pub /cmd_vel geometry_msgs/Twist '{}'
```

Of course this is not the most intuitive way to send commands. There is a joystick or gamepad node in the hector_quadrotor_teleop package which publishes cmd_vel. Or you have to write your own application-specific node to send velocity commands.
