### ISSUE TITLE
weird file name due to git ignore file

### ISSUE THREAD

**Issue by hannesharms** [tu-darmstadt-ros-pkg/hector_quadrotor#31]
The quadrotot plugin.gazebo.xacro in  hector_quadrotor_gazebo/urdf has a wired file name ending with .in
Maybe due to a wrong entry in the  git ignore file in the repo.

**Comment by meyerj** [comment]
That's intended. The actual file `quadrotor_plugins.gazebo.xacro` is generated by cmake depending on some compile time settings and availability of optional dependencies.
