### ISSUE TITLE
Catkin version of hector_quadrotor problems.

### ISSUE THREAD

**Issue by End-Effector** [tu-darmstadt-ros-pkg/hector_quadrotor#4]
Hello friend.

I'm trying to work with your catkin package but when I do the catkin_make it give me the following error:

CMake Error at /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:72 (find_package):
  Could not find a configuration file for package hector_pose_estimation.

This crashes the catkin make, and I can't build the package.

Do you have any ideia on how to solve this? How to build the package?

Thx so much for the help friend.

**Comment by meyerj** [comment]
hector_quadrotor requires some other hector packages like for example hector_pose_estimation.
You can install them either from the ROS Ubuntu repositories (recommended) or add a working copy of the source repo to your catkin workspace when building hector_quadrotor.

To install the packages from the Ubuntu repository:

```
cd ~/catkin_ws    # or whereever your workspace resides
rosdep install --from-path src --ignore-src     # This will install all required packages.
catkin_make
```

To clone the source repositories to your workspace:

```
cd ~/catkin_ws
wstool merge -t src https://raw.github.com/tu-darmstadt-ros-pkg/hector_quadrotor/hydro-devel/hector_quadrotor.rosinstall
wstool update
catkin_make
```

Please comment if none of the two approaches would work for you or if you have further questions.

**Comment by QuadRobo** [comment]
I have managed to catkin_make hector_quadrotor-catkin successfully after using the first step given by meyerj.
I have been trying to run the demo as per the tutorial in ROS.
rosmake doesn't work as it cannot find the makefile.
roslaunch also doesn't work, error listed below:

> while processing /opt/ros/hydro/share/hector_gazebo_worlds/launch/rolling_landscape_120m.launch:
> Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/opt/ros/hydro/share/hector_gazebo_worlds/launch/rolling_landscape_120m.launch'

Is there any other way?

**Comment by End-Effector** [comment]
You don't use rosmake if you used catkin...

You used catkin the package is built. Now you only need to use the command (source devel/setup.bash) and then you can use the roslaunch.

**Comment by meyerj** [comment]
The missing launch file is indeed a bug in the `CMakeLists.txt` file of the hector_gazebo_worlds package.
Fixed here: https://github.com/tu-darmstadt-ros-pkg/hector_gazebo/commit/18468640814aa919501bc4433b3696ac8fa64ef4

Until a new version is released you have to check out hector_gazebo from source if you are using the released package (just add it to your catkin workspace manually or using wstool):

```
wstool set hector_gazebo --git https://github.com/tu-darmstadt-ros-pkg/hector_gazebo.git` -v hydro-devel
wstool update hector_gazebo
```

**Comment by QuadRobo** [comment]
After a damned security update, my hydro links with gazebo has been removed. I reinstalled gazebo and have tested the connection successfully. I then delete my previous hector_quadrotor-catkin_ws and started from scratch. The same error appeared and this time using the same methods as described in meyerj 1st post, none of them works now. These are the error I received from the two methods respectively.

First method's error

> a9658007@mselinux01:~/hector_quad-catkin_ws$ rosdep install --from-path src --ignore-src
> executing command [sudo apt-get install ros-hydro-hector-gazebo-plugins]
> ...
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies.
> ros-hydro-hector-gazebo-plugins : Depends: gazebo but it is not going to be installed
>                                   Depends: sdformat but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> ERROR: the following rosdeps failed to install
> apt: command [sudo apt-get install ros-hydro-hector-gazebo-plugins] failed

Second method's error

> a9658007@mselinux01:~/hector_quad-catkin_ws$ wstool merge -t src https://raw.github.com/tu-darmstadt-ros-pkg/hector_quadrotor/hydro-devel/hector_quadrotor.rosinstall
> ERROR in config: /home/likewise-open/CAMPUS/a9658007/hector_quad-catkin_ws/src has no workspace configuration file '.rosinstall'

Any idea what is wrong?

**Comment by meyerj** [comment]
A similar problem was described on ROS answers a few days ago:
http://answers.ros.org/question/101976/ros-hydro-desktop-full-installs-gazebo-current-instead-of-gazebo/

Try to update your APT cache (sudo apt-get update) and then run rosdep again.
Or try to install gazebo manually first (sudo apt-get install gazebo) as mentioned in Angus' answer.

**Comment by meyerj** [comment]
> Second method's error
> 
> > a9658007@mselinux01:~/hector_quad-catkin_ws$ wstool merge -t src https://raw.github.com/tu-darmstadt-ros-pkg/hector_quadrotor/hydro-devel/hector_quadrotor.rosinstall
> > ERROR in config: /home/likewise-open/CAMPUS/a9658007/hector_quad-catkin_ws/src has no workspace configuration file '.rosinstall'
> 
> Any idea what is wrong?

Initialize the workspace first if you haven't done that before:

```
wstool init src
```

**Comment by QuadRobo** [comment]
> check out hector_gazebo from source if you are using the released package (just add it to your catkin workspace manually or using wstool)

By this do you mean downloading it and then putting it into the catkin_ws/src/hector_quadrotor-version folder?

**Comment by meyerj** [comment]
Do not clone hector_gazebo within hector_quadrotor. You can find a tutorial on how to setup a catkin workspace [here](http://wiki.ros.org/catkin/Tutorials/create_a_workspace).

wstool helps you to clone all source repositories in the `~/catkin_ws/src` folder. Once you did the first time setup you can follow the instructions in [my first answer](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/issues/4#issuecomment-28381974).

At the end you should end up with something like

```
~/catkin_ws
  |- build
  |- devel
  |   |- setup.bash
  |   |- ...
  |- src
      |- .rosinstall
      |- hector_quadrotor
      |- hector_localization
      |- hector_gazebo
      |- hector_models
```

**Comment by QuadRobo** [comment]
I do know how to create a ROS package. I was just wondering which level should the hector_gazebo be.
By the way after making catkin_make, we have to remember to: 

> source devel/setup.bash

After this I tried 

> roslaunch hector_quadrotor_demo indoor_slam_gazebo.launch

This error came up

> Traceback (most recent call last):
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/**init**.py", line 279, in main p.start()
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/parent.py", line 257, in start self._start_infrastructure()
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/parent.py", line 206, in _start_infrastructure self._load_config()
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/parent.py", line 121, in _load_config self.config = roslaunch.config.load_config_default(self.roslaunch_files, self.port, verbose=self.verbose)
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/config.py", line 428, in load_config_default loader.load(f, config, verbose=verbose)
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 698, in load self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 670, in _load_launch self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 634, in _recurse_load val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call return f(_args, *_kwds)
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 553, in _include_tag inc_filename = self.resolve_args(tag.attributes['file'].value, context)
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 159, in resolve_args return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 299, in resolve_args resolved = _resolve_args(resolved, context, resolve_anon, commands)
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 312, in _resolve_args resolved = commands[command](resolved, a, args, context)
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 137, in _find return _find_executable(resolve_without_path, a, [args[0], path], context)
> File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 173, in _find_executable full_path = _get_executable_path(rp.get_path(args[0]), path)
> File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 190, in get_path raise ResourceNotFound(name, ros_paths=self._ros_paths)
> ResourceNotFound: hector_slam_launch
> ROS path [0]=/opt/ros/hydro/share/ros
> ROS path [1]=/home/a9658007/catkin_ws/src
> ROS path [2]=/opt/ros/hydro/share
> ROS path [3]=/opt/ros/hydro/stacks

Guess I will have to find out what these means.

EDIT: I have downloaded this repository: https://github.com/tu-darmstadt-ros-pkg/hector_slam/tree/catkin
Hopefully this is the right one for the hector_slam_launch

**Comment by meyerj** [comment]
Ah, right. The demo package also requires hector_slam. However, it is not required to use hector_quadrotor in general, so I did not add it to the `hector_quadrotor.rosinstall` file.

There used to be a https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor_apps/raw/groovy-devel/tutorials.rosinstall file for groovy, but the [hector_quadrotor_apps](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor_apps) stack has been deprecated in hydro and this file has been lost since then.

We still have to release hector_quadrotor in hydro and update the tutorials in the wiki...

**Comment by QuadRobo** [comment]
I have successfully compiled and ran the simulation.
Gazebo opened successfully though I did not managed to see anything.
Reason being that my graphic card wasn't powerful enough to support Gazebo's requirement.
Getting a better GPU in the week.
