### ISSUE TITLE
Installing in ROS Jade

### ISSUE THREAD

**Issue by rshum19** [tu-darmstadt-ros-pkg/hector_quadrotor#42]
HI, 

Is it possible to install in ROS Jade? I'm having some issues doing so.

I cloned the indigo-devel branch into my catkin_ws/src folder. Then run the command catkin_make.

I go the error:

Could not find a package configuration file provided by
  "hector_pose_estimation" with any of the following names:

```
hector_pose_estimationConfig.cmake
hector_pose_estimation-config.cmake
```

thank you for the help

**Comment by meyerj** [comment]
hector_pose_estimation is a dependency of hector_quadrotor. I released hector_localization (which contains the hector_pose_estimation package), hector_gazebo and hector_models in jade today.
But you also need the ros_control and gazebo_ros_control packages, which are not yet available as binary packages for jade.

The new jade-devel branch of this repository should work, given that you also add all dependencies to your workspace. Check https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/blob/jade-devel/hector_quadrotor.rosinstall and additionally add the two 3rd-party repositories mentioned above:

```
cd src
wstool init .
wstool merge  https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/blob/jade-devel/hector_quadrotor.rosinstall
wstool set ros_control -v jade-devel --git https://github.com/ros-controls/ros_control.git
wstool set gazebo_ros_pkgs -v jade-devel --git https://github.com/ros-simulation/gazebo_ros_pkgs.git

wstool update
```

You should be able to built all these packages from source in ROS jade and then spawn a quadrotor, like in indigo.
