### ISSUE TITLE
rviz error in hector_quadrotor_demo

### ISSUE THREAD

**Issue by ghost** [tu-darmstadt-ros-pkg/hector_quadrotor#47]
I have source installed hector quadrotor demo .When i roslaunch outdoor_ flight_gazebo the gazebo window pops up with the simulation but the rviz gets killed..i cant figure out why this happens ...
the error o/p is as follows:

[rviz-8] process has died [pid 29273, exit code -11, cmd /home/azar/ros_catkin_ws/install_isolated/lib/rviz/rviz -d /home/azar/hector_quadrotor_tutorial/src/hector_quadrotor/hector_quadrotor_demo/rviz_cfg/outdoor_flight.rviz __name:=rviz __log:=/home/azar/.ros/log/b02e4b10-ba10-11e5-9ade-c038966edbf9/rviz-8.log].
log file: /home/azar/.ros/log/b02e4b10-ba10-11e5-9ade-c038966edbf9/rviz-8*.log

**Comment by nicolaerosia** [comment]
What's in the log file?

**Comment by ghost** [comment]
This problem was solved later when I reinstalled ubuntu+ros
