### ISSUE TITLE
hector_quadrotor catkin problems still.

### ISSUE THREAD

**Issue by End-Effector** [tu-darmstadt-ros-pkg/hector_quadrotor#5]
Hello friend. You responded to my other question but I still have problems.

I'm trying to use this catkin version https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/tree/catkin. In this version there is a folder with hector_pose_estimation. I don't understand why the catkin_make can't find it. I think all the necessary folders are there.

You closed the other one, I'm sorry I don't want to disrespect you in any way by opening a new issue.

**Comment by meyerj** [comment]
Please don't open new issues. You can still comment on issue #4.

There is no hector_pose_estimation folder in the hector_quadrotor repository, only hector_quadrotor_pose_estimation, which depends on hector_pose_estimation. Please first try to install or clone all dependent packages before reporting new issues.

Furthermore you should switch to the hydro-devel branch. catkin was a working branch which probably should be deleted. Did you find a reference to the catkin branch somewhere in the Wiki or on ROS answers?
