### ISSUE TITLE
Path not correctly set inside spawn_quadrotor_with_asus_with_kinect.launch

### ISSUE THREAD

**Issue by yazdani** [tu-darmstadt-ros-pkg/hector_quadrotor#55]
There exists no file by this ending:

arg name="model" value="$(find hector_quadrotor_description)/urdf/quadrotor_with_asus_with_hokuyo_**utm30lx.xacro**"

"**gazebo.xacro**" is missing here.

**Comment by meyerj** [comment]
Fixed. Thanks for reporting!
