### ISSUE TITLE
Can I control the quadrotor with attitude commands?

### ISSUE THREAD

**Issue by chutsu** [tu-darmstadt-ros-pkg/hector_quadrotor#58]
I dived into the code a little bit and found that you can set the control mode in the teleop package from twist to attitude, there appears to also be a Attitude command handler. 

My question is therefore how can I actually control the attitude?
What configurations do I have to change to do this?

**Comment by meyerj** [comment]
This feature was added in the [kinetic-devel](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/tree/kinetic-devel) branch in https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/pull/57, but it still lacks some documentation. Basically you can set the `control_mode` parameter (or roslaunch argument) of the teleop node to `"attitude"`. Also adapt the axes and buttons in the respective launch file depending on your controller hardware and preferences.

The simulated quadrotor accepts commands on various topics and has limited support for control mode switches now.
