### ISSUE TITLE
at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):   Could not find a package configuration file provided by   "hardware_interface" with any of the following names:

### ISSUE THREAD

**Issue by yueshukun** [tu-darmstadt-ros-pkg/hector_quadrotor#76]
While running the following commands:
mkdir ~/hector_quadrotor_tutorial
cd ~/hector_quadrotor_tutorial
wstool init src https://raw.github.com/tu-darmstadt-ros-pkg/hector_quadrotor/kinetic-devel/tutorials.rosinstall
catkin_make
source devel/setup.bash

**# I got the following error:**
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by
  "hardware_interface" with any of the following names:

    hardware_interfaceConfig.cmake
    hardware_interface-config.cmake

  Add the installation prefix of "hardware_interface" to CMAKE_PREFIX_PATH or
  set "hardware_interface_DIR" to a directory containing one of the above
  files.  If "hardware_interface" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  hector_quadrotor/hector_quadrotor_interface/CMakeLists.txt:4 (find_package)

-- Could not find the required component 'hardware_interface'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "hardware_interface" with any of the following names:

    hardware_interfaceConfig.cmake
    hardware_interface-config.cmake

  Add the installation prefix of "hardware_interface" to CMAKE_PREFIX_PATH or
  set "hardware_interface_DIR" to a directory containing one of the above
  files.  If "hardware_interface" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  hector_quadrotor/hector_quadrotor_interface/CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/yueshukun/hector_quadrotor_tutorial/build/CMakeFiles/CMakeOutput.log".
See also "/home/yueshukun/hector_quadrotor_tutorial/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by suraj2596** [comment]
`rosdep install --from-path src --ignore-src --rosdistro lunar`
