### ISSUE TITLE
catkin_make failure

### ISSUE THREAD

**Issue by Ste1989** [tu-darmstadt-ros-pkg/hector_quadrotor#8]
Hi, i have donwloaded the all required packages from the repository and put them into a directory hector_quadrotor/src. When i want build  the catkin workspace as usual:

cd hector_quadrotor/src
 catkin_init_workspace
 cd .. catkin_make

i find this error: make[2]: \* No rule to make target /usr/lib/libflann_cpp_s.a', needed by/home/stefano/Desktop/hector_quad/devel/lib/libhector_quadrotor_controller_gazebo.so'. Stop.

what can i do? Thanks to all

**Comment by Ste1989** [comment]
i have ROS HYDRO on Ubuntu 13.04

**Comment by meyerj** [comment]
Has this been solved in the meantime? It could have been a dependency problem what has been solved in early hydro releases. We do not use flann directly in hector_quadrotor.
